server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: nugux-api-server

logging:
  level:
    org:
      springframework:
        security: info
        boot: info
        web: info